sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mikecigaw/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mikecigaw/react-test npm test 

after_success:
  - docker build -t mikecigaw/multi-client ./client 
  - docker build -t mikecigaw/multi-nginx ./nginx 
  - docker build -t mikecigaw/multi-server ./server
  - docker build -t mikecigaw/multi-worker ./worker 
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take above images and push to docker hub
  - docker push mikecigaw/multi-client
  - docker push mikecigaw/multi-nginx
  - docker push mikecigaw/multi-server
  - docker push mikecigaw/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-711681966202'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
